name: API Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Newman Tests
        env:
          REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
        run: |
          newman run postman/ReqRes_API_QA_Portfolio.postman_collection.json \
          --env-var "baseUrl=https://reqres.in" \
          --env-var "api-key=$REQRES_API_KEY"
